### PR TITLE
Remove duplicate instances

### PR DESCRIPTION
**Pull request by mietek**
Necessary to compile with `haste-compiler` 0.5, which is soon to be released.

### CODE REVIEW

**Comment by mietek** [comment]
Ping?

**Comment by lepinay** [comment]
It would be nice to merge that one, I wanted to play with perch this weekend, but I can't install it...I'm also having a few "Attribute"/"attr" ambiguous errors.

**Comment by agocorona** [comment]
I though that this was already merged. Sorry

**Comment by agocorona** [comment]
@lepinay can you detail the errors?

**Comment by lepinay** [comment]
Sure, here is my log after running the command "cabal install haste-perchl" (I'm on windows with cabal-install version 1.18.0.5 and haste 0.4.4)

Building haste-perch-0.1.0.5...
Preprocessing library haste-perch-0.1.0.5...
[1 of 2] Compiling Haste.App.Perch  ( Haste\App\Perch.hs, dist\build\Haste\App\Perch.o )

Haste\App\Perch.hs:243:14:
    Ambiguous occurrence `Attribute'
    It could refer to either `Haste.App.Perch.Attribute',
                             defined at Haste\App\Perch.hs:240:1
                          or `Haste.App.Attribute',
                             imported from `Haste.App' at Haste\App\Perch.hs:21:1-16
                             (and originally defined in `Haste.DOM')

Haste\App\Perch.hs:246:28:
    Ambiguous occurrence `attr'
    It could refer to either `Haste.App.Perch.attr',
                             defined at Haste\App\Perch.hs:69:1
                          or `Haste.App.attr',
                             imported from `Haste.App' at Haste\App\Perch.hs:21:1-16
                             (and originally defined in `Haste.DOM')

Haste\App\Perch.hs:249:8:
    Ambiguous occurrence `attr'
    It could refer to either `Haste.App.Perch.attr',
                             defined at Haste\App\Perch.hs:69:1
                          or `Haste.App.attr',
                             imported from `Haste.App' at Haste\App\Perch.hs:21:1-16
                             (and originally defined in `Haste.DOM')

**Comment by agocorona** [comment]
Ok,
That is because you have imported both Haste.Perch and Haste.App.Perch


use either one or the other.  The second is only for applications that use Haste.App, that is, the ones that use the Client monad. It contains the same primitives, but for this monad instead of IO

**Comment by lepinay** [comment]
Thanks @agocorona I'm actually trying to follow the instructions here (to get started and learn): https://github.com/agocorona/hplayground.

And that's when I type "haste-inst install haste-perch" that I get the error...so i'm a bit confused right now...

**Comment by lepinay** [comment]
@agocorona I'm actually following the steps in https://github.com/agocorona/hplayground to get started, and that's when I typed "haste-inst install" so I'm a bit confused now...

**Comment by agocorona** [comment]
lepinay when comiling haste-perch or when compiling hplayground?  I´m trying to reproduce the error but I can´t .  which compiler version etc do you use?

**Comment by lepinay** [comment]
@agocorona it actually happens earlier when typing "haste-inst install haste-perch" when following https://github.com/agocorona/hplayground. I've tried it both on windows and in an ubuntu docker container (I've used 
"docker run -it --rm haskell bash", if you would like to try to reproduce in docker).

**Comment by agocorona** [comment]
I will try. 

In the meantime you can use this docker container, that haskell, haste, perch and hplayground installed:

https://registry.hub.docker.com/u/agocorona/tryhplay/

**Comment by agocorona** [comment]
Fixed.

The problem was because Haste.DOM included two new identifiers: Attribute and attr that collides with both  Perch.hs

**Comment by agocorona** [comment]
I published a new version of Haste-perch in hackage and git

**Comment by lepinay** [comment]
Thanks @agocorona

**Pull request merged**
